### PR TITLE
Support adaptive icons

### PR DESCRIPTION
**Pull request by nbruning**
This PR supports [adaptive icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive).

The adaptive icon is a xml file, which in turn can refer to a vector xml drawable.

The code creates a new xml drawable using `<layer-list>`, which stacks the original icon and the generated overlay.

Because adaptive icons are round, the placement of the text is changed to be vertically centered for adaptive icons. For normal icons, the placement is unchanged.

### CODE REVIEW

**Comment by nbruning** [comment]
Thanks @itolianezzz, are you planning to release 1.0.3 to the gradle plugins repo anytime soon?

**Comment by itolianezzz** [comment]
@nbruning yeah, it already on review in plugins repository. Should be there in 1-2 days

**Comment by creati8e** [comment]
> @nbruning yeah, it already on review in plugins repository. Should be there in 1-2 days

It should be published instantly without any delay.

**Comment by creati8e** [comment]
@nbruning hi! I've found that you use original foreground which is processed with plugin too. So it results in icon with badge overlayed twice.

**Comment by nbruning** [comment]
@creati8e Just letting you know, I will be pushing a fix at some point, but right now can't find the time.

**Pull request merged**
